[package]
name = "skewheap"
version = "0.1.0"
edition = "2018"
authors = ["Jeff Ober <sysread@fastmail.fm>"]

[lib]
name = "skewheap"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "^0.3"
rand = "*"

[[bench]]
name = "benchmark"
harness = false
